# Write a Python function to sort a list of dictionaries by a specific key
data = [
    {"name": "Alice", "age": 25},
    {"name": "Bob", "age": 30},
    {"name": "Charlie", "age": 20},
]
def sort_dicts_by_key(data, key):
    return sorted(data, key=lambda x: x[key])
sorted_data = sort_dicts_by_key(data, "age")
print(sorted_data)


# The above code has been generated by Github Copilot


# Comparision
# CUSTOM FUNCTION TO SORT A LIST OF DICTIONARIES BY A SPECIFIED KEY
data = [
    {"name": "Washington", "age": 24},
    {"name": "Veronicah", "age": 21},
    {"name": "Ashimala", "age": 22}
]
def sort(data, key):
    return sorted(data, key=lambda x: x[key])

print(sort(data, "age"))

# Washington Mwangi